# Generated by Django 3.2.11 on 2022-07-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/processed-files'),
        ),
    ]
