# Generated by Django 3.2.11 on 2022-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkapp', '0002_file_processed_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='processed_json_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/processed-json-files'),
        ),
    ]
